[package]
name = "echo-bot"
version = "0.1.0"
authors = ["Ravi Shankar <wafflespeanut@gmail.com>"]

[dependencies.beryllium]
path = "../../"

[dependencies]
chrono = "0.4"
env_logger = "0.4"
log = "0.3"
